# Generated by Django 3.0.4 on 2020-03-10 15:17

import core.models
from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_services_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to=core.models.get_file_name, verbose_name='Imagem'),
        ),
    ]
